resolver: lts-5.2

packages:
- '.'

extra-deps:
- ADPfusion-0.5.1.0
- BiobaseNewick-0.0.0.1
- cereal-text-0.1.0.1
- ForestStructures-0.0.0.1
- FormalGrammars-0.3.0.0
- GrammarProducts-0.1.1.2
- hybrid-vectors-0.2.1
- OneTuple-0.2.1
- OrderedBits-0.0.1.0
- PrimitiveArray-0.7.0.1
- PrimitiveArray-Pretty-0.0.0.1
- tuple-0.3.0.2

flags:
  ADPfusionForest:
    examples: true

extra-package-dbs: []

